-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_Filter_v7_IP\Butter_TP_4_1000_v1_dut.vhd
-- Created: 2025-06-11 16:58:32
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Butter_TP_4_1000_v1_dut
-- Source Path: Butter_TP_4_1000_v1/Butter_TP_4_1000_v1_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Butter_TP_4_1000_v1_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        In2                               :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Out2                              :   OUT   std_logic  -- ufix1
        );
END Butter_TP_4_1000_v1_dut;


ARCHITECTURE rtl OF Butter_TP_4_1000_v1_dut IS

  -- Component Declarations
  COMPONENT Butter_TP_4_1000_v1_src_Biquad_Filtrer
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          In2                             :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          Out1                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Out2                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Butter_TP_4_1000_v1_src_Biquad_Filtrer
    USE ENTITY work.Butter_TP_4_1000_v1_src_Biquad_Filtrer(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In2_sig                          : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Out1_sig                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Out2_sig                         : std_logic;  -- ufix1

BEGIN
  u_Butter_TP_4_1000_v1_src_Biquad_Filtrer : Butter_TP_4_1000_v1_src_Biquad_Filtrer
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              In1 => In1,  -- sfix32_En16
              In2 => In2_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              Out1 => Out1_sig,  -- sfix32_En16
              Out2 => Out2_sig  -- ufix1
              );

  In2_sig <= In2;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  Out1 <= Out1_sig;

  Out2 <= Out2_sig;

END rtl;

