-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_Filter_v8_IP_2\LP_Butter_2_1kHz_fix32_16_v2_src_BiquadDF2Section1.vhd
-- Created: 2025-06-26 16:35:56
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LP_Butter_2_1kHz_fix32_16_v2_src_BiquadDF2Section1
-- Source Path: biquad_Filter_v8_IP_2/Biquad Filtrer/Biquad Filter/BiquadDF2Section1
-- Hierarchy Level: 2
-- Model version: 1.107
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LP_Butter_2_1kHz_fix32_16_v2_src_BiquadDF2Section1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        validOut                          :   OUT   std_logic
        );
END LP_Butter_2_1kHz_fix32_16_v2_src_BiquadDF2Section1;


ARCHITECTURE rtl OF LP_Butter_2_1kHz_fix32_16_v2_src_BiquadDF2Section1 IS

  -- Signals
  SIGNAL dataIn_signed                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL inReg                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL numPrePipe1                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL numProd1                         : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL numPostPipe1                     : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL inValidReg                       : std_logic;
  SIGNAL intdelay_reg                     : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL inValidRegDly                    : std_logic;
  SIGNAL numPrePipe2                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL numProd2                         : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL numPostPipe2                     : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL numPrePipe3                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL numProd3                         : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL numPostPipe3                     : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL denOut                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL denProd1                         : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL denProd2                         : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL adder_add_cast                   : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL adder_add_cast_1                 : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL denSum3                          : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL state2                           : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL adder_add_cast_2                 : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL denSum2b                         : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL adder_add_cast_3                 : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL denSum2a                         : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL state1                           : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL adder_add_cast_4                 : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL denSum1                          : signed(65 DOWNTO 0);  -- sfix66_En46
  SIGNAL dataOut_tmp                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL intdelay_reg_1                   : std_logic_vector(3 DOWNTO 0);  -- ufix1 [4]

BEGIN
  dataIn_signed <= signed(dataIn);

  InRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inReg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        inReg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS InRegister_process;


  numPreReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPrePipe1 <= inReg;
      END IF;
    END IF;
  END PROCESS numPreReg1_process;


  numProd1 <= to_signed(538228350, 32) * numPrePipe1;

  numPostReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe1 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        numPostPipe1 <= numProd1;
      END IF;
    END IF;
  END PROCESS numPostReg1_process;


  InValidRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inValidReg <= '0';
      ELSIF enb = '1' THEN
        inValidReg <= validIn;
      END IF;
    END IF;
  END PROCESS InValidRegister_process;


  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        intdelay_reg(0) <= inValidReg;
        intdelay_reg(1) <= intdelay_reg(0);
      END IF;
    END IF;
  END PROCESS intdelay_process;

  inValidRegDly <= intdelay_reg(1);

  numPreReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPrePipe2 <= inReg;
      END IF;
    END IF;
  END PROCESS numPreReg2_process;


  numProd2 <= to_signed(1076456700, 32) * numPrePipe2;

  numPostReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe2 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        numPostPipe2 <= numProd2;
      END IF;
    END IF;
  END PROCESS numPostReg2_process;


  numPreReg3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe3 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPrePipe3 <= inReg;
      END IF;
    END IF;
  END PROCESS numPreReg3_process;


  numProd3 <= to_signed(538228350, 32) * numPrePipe3;

  numPostReg3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe3 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        numPostPipe3 <= numProd3;
      END IF;
    END IF;
  END PROCESS numPostReg3_process;


  denProd1 <= to_signed(1949207645, 32) * denOut;

  denProd2 <= to_signed(-892285457, 32) * denOut;

  adder_add_cast <= resize(numPostPipe3(63 DOWNTO 7), 66);
  adder_add_cast_1 <= resize(denProd2, 66);
  denSum3 <= adder_add_cast + adder_add_cast_1;

  State2Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state2 <= to_signed(0, 66);
      ELSIF enb = '1' AND inValidRegDly = '1' THEN
        state2 <= denSum3;
      END IF;
    END IF;
  END PROCESS State2Reg_process;


  adder_add_cast_2 <= resize(numPostPipe2(63 DOWNTO 7), 66);
  denSum2b <= adder_add_cast_2 + state2;

  adder_add_cast_3 <= resize(denProd1, 66);
  denSum2a <= denSum2b + adder_add_cast_3;

  State1Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state1 <= to_signed(0, 66);
      ELSIF enb = '1' AND inValidRegDly = '1' THEN
        state1 <= denSum2a;
      END IF;
    END IF;
  END PROCESS State1Reg_process;


  adder_add_cast_4 <= resize(numPostPipe1(63 DOWNTO 7), 66);
  denSum1 <= adder_add_cast_4 + state1;

  denOut <= denSum1(61 DOWNTO 30);

  outputReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_tmp <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        dataOut_tmp <= denOut;
      END IF;
    END IF;
  END PROCESS outputReg_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg_1 <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        intdelay_reg_1(0) <= validIn;
        intdelay_reg_1(3 DOWNTO 1) <= intdelay_reg_1(2 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_1_process;

  validOut <= intdelay_reg_1(3);

END rtl;

