# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/audio_test/audio_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test || ORIG_REF_NAME==audio_test} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_processing_system7_0_0/audio_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_processing_system7_0_0 || ORIG_REF_NAME==audio_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_audio_codec_ctrl_0_0/audio_test_audio_codec_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_audio_codec_ctrl_0_0 || ORIG_REF_NAME==audio_test_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_xbar_0/audio_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_xbar_0 || ORIG_REF_NAME==audio_test_xbar_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_ps7_0_axi_periph_0/audio_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==audio_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_proc_sys_reset_0_0/audio_test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_proc_sys_reset_0_0 || ORIG_REF_NAME==audio_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_dma_0_5/audio_test_axi_dma_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_dma_0_5 || ORIG_REF_NAME==audio_test_axi_dma_0_5} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_rst_ps7_0_50M_3/audio_test_rst_ps7_0_50M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_rst_ps7_0_50M_3 || ORIG_REF_NAME==audio_test_rst_ps7_0_50M_3} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_xbar_1/audio_test_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_xbar_1 || ORIG_REF_NAME==audio_test_xbar_1} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_mem_intercon_5/audio_test_axi_mem_intercon_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_mem_intercon_5 || ORIG_REF_NAME==audio_test_axi_mem_intercon_5} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_xbar_2/audio_test_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_xbar_2 || ORIG_REF_NAME==audio_test_xbar_2} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_mem_intercon_1_4/audio_test_axi_mem_intercon_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_mem_intercon_1_4 || ORIG_REF_NAME==audio_test_axi_mem_intercon_1_4} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_dma_0_6/audio_test_axi_dma_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_dma_0_6 || ORIG_REF_NAME==audio_test_axi_dma_0_6} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_dma_HP_0/audio_test_axi_dma_HP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_dma_HP_0 || ORIG_REF_NAME==audio_test_axi_dma_HP_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_axi_dma_TP_0/audio_test_axi_dma_TP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_axi_dma_TP_0 || ORIG_REF_NAME==audio_test_axi_dma_TP_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_BS_Butter_2_500Hz_2k_0_0/audio_test_BS_Butter_2_500Hz_2k_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_BS_Butter_2_500Hz_2k_0_0 || ORIG_REF_NAME==audio_test_BS_Butter_2_500Hz_2k_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_BP_Butter_2_500Hz_2k_0_0/audio_test_BP_Butter_2_500Hz_2k_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_BP_Butter_2_500Hz_2k_0_0 || ORIG_REF_NAME==audio_test_BP_Butter_2_500Hz_2k_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_LP_Butter_2_1kHz_fix_0_0/audio_test_LP_Butter_2_1kHz_fix_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_LP_Butter_2_1kHz_fix_0_0 || ORIG_REF_NAME==audio_test_LP_Butter_2_1kHz_fix_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_HP_Butter_2_1kHz_fix_0_0/audio_test_HP_Butter_2_1kHz_fix_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_HP_Butter_2_1kHz_fix_0_0 || ORIG_REF_NAME==audio_test_HP_Butter_2_1kHz_fix_0_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_pc_0/audio_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_pc_0 || ORIG_REF_NAME==audio_test_auto_pc_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_cc_0/audio_test_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_cc_0 || ORIG_REF_NAME==audio_test_auto_cc_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_cc_1/audio_test_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_cc_1 || ORIG_REF_NAME==audio_test_auto_cc_1} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_cc_2/audio_test_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_cc_2 || ORIG_REF_NAME==audio_test_auto_cc_2} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_cc_3/audio_test_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_cc_3 || ORIG_REF_NAME==audio_test_auto_cc_3} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_pc_1/audio_test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_pc_1 || ORIG_REF_NAME==audio_test_auto_pc_1} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_us_0/audio_test_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_us_0 || ORIG_REF_NAME==audio_test_auto_us_0} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_us_1/audio_test_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_us_1 || ORIG_REF_NAME==audio_test_auto_us_1} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_us_2/audio_test_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_us_2 || ORIG_REF_NAME==audio_test_auto_us_2} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_us_3/audio_test_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_us_3 || ORIG_REF_NAME==audio_test_auto_us_3} -quiet] -quiet

# IP: bd/audio_test/ip/audio_test_auto_pc_2/audio_test_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_test_auto_pc_2 || ORIG_REF_NAME==audio_test_auto_pc_2} -quiet] -quiet

# XDC: f:/MyGit_Folder/Thesis-Funkner-Schwarz/filter_implementierung/vivado/Audio_quad_Filter_v1/Audio_quad_Filter_v1.gen/sources_1/bd/audio_test/audio_test_ooc.xdc
