# Filterung einer WAV Datei

Zur Demonstration von digitalen Filtern auf Mikrocontrollern wird eine WAV-Datei mittels eines ESP32 gefiltert. Die Audio-Datei wird über eine SD-Karte eingelesen, gefiltert und als gefilterte Variante abgespeichert. 

Zu beachten ist, dass nur 16-Bit-WAV-Dateien unterstützt werden. Die Datei kann jedoch Mono oder Stereo mit und einer beliebigen Samplerate sein. Die WAV-Datei, die gefiltert werden soll, muss zu `original.wav` umbenannt werden bevor diese auf die SD-Karte übertragen wird.

## Vorbereitung der WAV-Filterung

```cpp
#include "SD_MMC.h" // SD-Karten-Support für ESP32 mit SD_MMC-Anschluss
```
Durch die Einbindung vom SD_MMC.h wird eine erleichterte Nutzung von SD-Karten mit einem ESP32 geboten, als auch die Möglichkeit für 1-Wire-Modus sowie 4-Wire-Modus.

```cpp
// --- WAV Hilfsfunktionen ---
uint32_t readLEUint32(uint8_t* buf) {
  return (uint32_t)buf[0] | ((uint32_t)buf[1] << 8) | ((uint32_t)buf[2] << 16) | ((uint32_t)buf[3] << 24);
}
uint16_t readLEUint16(uint8_t* buf) {
  return (uint16_t)buf[0] | ((uint16_t)buf[1] << 8);
}
```
Diese Hilfsfunktionen konvertieren Byte-Arrays aus WAV-Dateien in Ganzzahlen im Little-Edian-Format um. `readLEUint32()` kombiniert 4 Bytes zu einem 32-Bit-wert, `readLEUint16()` kombiniert 2 Bytes zu einem 16-Bit-Wert, wobei das niedrigste Byte zuerst kommt.

```cpp
// WAV-Header für die Ausgabedatei schreiben
void writeWavHeader(File &file, uint32_t dataSize, uint16_t channels, uint32_t sampleRate, uint16_t bitsPerSample) {
  const char* riff = "RIFF";
  const char* wave = "WAVE";
  const char* fmt  = "fmt ";
  const char* data = "data";

  uint32_t chunkSize = 36 + dataSize;
  uint16_t blockAlign = channels * bitsPerSample / 8;
  uint32_t byteRate = sampleRate * blockAlign;
  uint32_t subchunk1Size = 16;
  uint16_t audioFormat = 1; // PCM

  file.seek(0);
  file.write((const uint8_t*)riff, 4);
  file.write((uint8_t*)&chunkSize, 4);
  file.write((const uint8_t*)wave, 4);
  file.write((const uint8_t*)fmt, 4);
  file.write((uint8_t*)&subchunk1Size, 4);
  file.write((uint8_t*)&audioFormat, 2);
  file.write((uint8_t*)&channels, 2);
  file.write((uint8_t*)&sampleRate, 4);
  file.write((uint8_t*)&byteRate, 4);
  file.write((uint8_t*)&blockAlign, 2);
  file.write((uint8_t*)&bitsPerSample, 2);
  file.write((const uint8_t*)data, 4);
  file.write((uint8_t*)&dataSize, 4);
}
```
Die `writeWavHeader`-Funktion schreibt einen WAV-Header in die Ausgabedatei. Die Funktion erstellt die erforderlichen Chunks (RIFF, WAVE, fmt, data) mit den übergebenen Audio-Parametern und berechnet automatisch die abgeleiteten Werte wie Byte-Rate und Block-Alignment. Der Header wird im Little-Endian-Format geschrieben.


```cpp
// --- Variablen für die Ein- und Ausgangsdatei --
File wavFile;       // Originale Eingangsdatei
File filteredFile;  // Gefiltere Ausgangsdatei

```
Hilfsvariablen für die originale Eingangsdatei als auch die gefilterte Ausgangsdatei.


Der Gesamtprozess bestehend aus einlesen, filtern und neuen WAV-Datei erstellen wird innerhalb der `Setup()`-Funktion durchgeführt.

```cpp
void setup() {
  Serial.begin(115200);
```
Zunächst wird die serielle Kommunikation mit 115200 Baud initialisiert, um Informationen des Mikrocontroller in der Konsole auslesen zu können.

```cpp
  // SD-Karte im 4-Wire Modus initialisieren
  if (!SD_MMC.begin("/sdcard", false)) {  //false = 4-Wire, true - 1-Wire
    Serial.println("Fehler beim Initialisieren der SD-Karte.");
    return;
  }
  Serial.println("SD-Karte gefunden.");
```
Die SD-Karte wird im 4-Wire-Modus initialisiert, welcher eine höhere Datenübertragungsrate ermöglicht als der 1-Wire-Modus. Durch den Parameter `false` wird der 4-Wire-Modus aktiviert, während `true` den 1-Wire-Modus aktiviert. Wird keine SD-Karte gefunden oder besteht ein Problem bei der Initialisierung, wird eine Fehlermeldung ausgegeben und das Programm beendet.

```cpp
  // Eingangs WAV Datei öffnen
  wavFile = SD_MMC.open("/original.wav", FILE_READ);
  if (!wavFile) {
    Serial.println("Fehler beim Öffnen der WAV-Datei.");
    return;
  }

  // WAV Header auslesen
  if (!readWavHeader()) {
    wavFile.close();
    return;
  }
```
Die originale WAV-Datei wird im Lesemodus geöffnet. Für den Fall, dass das Öffnen fehlschlägt, wird dementsprechende Fehlermeldung ausgegeben und das Programm beendet. Bei erfolgreichen Öffnen wird die Funktion `readWavHeader` aufgerufen und der Header der Eingangsdatei analysiert. Falls diese Funktion `false` zurückgibt, wird die Datei geschlossen und das Programm beendet.

```cpp
bool readWavHeader() {
  uint8_t riffHeader[12];
  if (wavFile.read(riffHeader, 12) != 12) {
    Serial.println("Fehler beim Lesen des RIFF-Headers.");
    return false;
  }
  //Prüfen auf "RIFF" und "WAVE"
  if (memcmp(riffHeader, "RIFF", 4) != 0 || memcmp(&riffHeader[8], "WAVE", 4) != 0) {
    Serial.println("Keine gültige WAV-Datei.");
    return false;
  }
```
Die Header-Analyse-Funkion beginnt mit der Validierung der WAV-Datei Signatur. Dazu werden die ersten 12 Bytes der Datei gelesen, die den RIFF-Header bilden. Anschließend wird überprüft, ob die Bytes 0-3 die Zeichenkette "RIFF" und die Bytes 8-11 die Zeichenkette "WAVE" enthalten. Diese Signaturen sind für alle gültigen WAV-Dateien notwendig und identifizieren das genaue Dateiformat.

```cpp
  // Variablen für WAV-Informationen
  uint16_t audioFormat = 0, numChannels = 0, bitsPerSample = 0;
  uint32_t sampleRate = 0, dataSize = 0;
  bool fmtFound = false, dataFound = false;
```
Für die Chunk-Analyse werden die folgenden Variablen initialisiert, welche die Audio-Parameter speichern. Die 16-Bit Variablen `audioFormat`, `numChannels` und `bitsPerSample` enthalten die grundlegenden Format-Informationen, während `sampleRate` und `dataSize` als 32-Bit-Werte die Abtastrate und Datengröße speichern. Die booleschen Flags `fmtFound` und `dataFound` verfolgen, die notwendigen Chunks bereits gefunden wurden.

```cpp
  // Suche nach "fmt " und "data" Chunks
  while (wavFile.position() < wavFile.size()) {
    uint8_t chunkHeader[8];
    if (wavFile.read(chunkHeader, 8) != 8) {
      Serial.println("Fehler beim Lesen eines Chunk-Headers.");
      break;
    }
    uint32_t chunkSize = readLEUint32(&chunkHeader[4]);
```
Der Chunk-Parser durchläuft systematisch die WAV-Datei, um relevante Datenabschnitte zu finden. Die WAV-Datei ist in Chunks unterteilt, die jeweils mit einem 8-Byte-Header beginnt: 4 Bytes für die Chunk-ID und 4 Bytes für die Größe im Little-Endian-Format. Die Schleife läuft bis zum Dateiende oder bis ein Lesefehler auftritt.

```cpp
    //Format-Chunk gefunden
    if (memcmp(chunkHeader, "fmt ", 4) == 0) {
      uint8_t fmtChunk[chunkSize];
      if (wavFile.read(fmtChunk, chunkSize) != chunkSize) {
        Serial.println("Fehler beim Lesen des fmt-Chunks.");
        break;
      }
      audioFormat = readLEUint16(&fmtChunk[0]);
      numChannels = readLEUint16(&fmtChunk[2]);
      sampleRate = readLEUint32(&fmtChunk[4]);
      bitsPerSample = readLEUint16(&fmtChunk[14]);
      fmtFound = true;

      // Parameter der Eingangs-WAV
      Serial.printf("AudioFormat: %d\n", audioFormat);
      Serial.printf("Kanäle: %d\n", numChannels);
      Serial.printf("SampleRate: %d\n", sampleRate);
      Serial.printf("Bits pro Sample: %d\n", bitsPerSample);

      if (chunkSize % 2 == 1) wavFile.seek(wavFile.position() + 1);
    }
```
Wenn der Chunk-Header "fmt" gefunden wird, werden die Chunk-Daten in einen Puffer geladen und die wichtigsten Audio-Parameter extrahiert: Audi-Format(PCM), Kanalzahl(Mono oder Stereo), Samplerate und die Bits pro Sample aus festen Byte-Positionen. Die Parameter werden zur Kontrolle ausgegeben und bei ungerader Chunk-Größe wird ein Padding-Byte übersprungen.

```cpp
    // Daten-Chunk gefunden
    else if (memcmp(chunkHeader, "data", 4) == 0) {
      dataSize = chunkSize;
      dataFound = true;
      break;
    }
```
Der Data-Chunk enthält die eigentlichen Audio-Daten mit den Samples. Sobald dieser gefunden wird, wird seine Größe gespeichert und die Suche endet. Der Dateizeiger steht dann am Beginn der Audio-Samples für die weitere Verarbeitung.

```cpp
    // Irrelavante Chucks überspringen
    else {
      wavFile.seek(wavFile.position() + chunkSize);
      if (chunkSize % 2 == 1) wavFile.seek(wavFile.position() + 1);
    }
  }
```
Irrelevante Chunks, wie LIST oder INFO, werden übersprungen, indem der Dateizeiger um die Chunk-Größe voranbewegt wird. Bei ungerader Chunk-Größe wird ein zusätzliches Padding-Byte übersprungen.

```cpp
  // Überprüfen ob alle nötigen Informationen gefunden wurden
  if (!fmtFound || !dataFound) {
    Serial.println("WAV-Header unvollständig oder Datenchunk nicht gefunden.");
    return false;
  }

  if (audioFormat != 1) {
    Serial.println("Nur PCM WAV-Dateien werden unterstützt.");
    return false;
  }

  if (bitsPerSample != 16) {
    Serial.println("Nur 16-Bit PCM wird unterstützt.");
    return false;
  }

  if (numChannels != 1 && numChannels != 2) {
    Serial.println("Nur Mono oder Stereo wird unterstützt.");
    return false;
  }
```
Es wird überprüft, ob Format- und Data-Chunk gefunden wurden und ob die Datei das kompatible Format besitzt. Entspricht die Datei nicht dem vorgesetzten Format wird eine Fehlermeldung ausgeben und das Programm beendet.

```cpp
  // Ausgabedatei erstellen und Header schreiben
  filteredFile = SD_MMC.open("/gefiltert.wav", FILE_WRITE);
  if (!filteredFile) {
    Serial.println("Fehler beim Öffnen der Ausgabedatei.");
    return false;
  }

  writeWavHeader(filteredFile, dataSize, numChannels, sampleRate, bitsPerSample);

  Serial.printf("Gesamtanzahl Frames (Samples pro Kanal): %d\n", dataSize / (numChannels * bitsPerSample / 8));
  Serial.println("Starte Filterung...");

  // Filterprozess starten
  filterAudio(numChannels, dataSize, bitsPerSample);

  Serial.println("Filterung abgeschlossen.");

  wavFile.close();
  filteredFile.close();

  return true;
```
Die Ausgabedatei "gefiltert.wav" wird im Schreibmodus erstellt und erhält einen neuen WAV-Header mit den identischen Parametern der Eingangsdatei. Würde man keinen neuen WAV-Header erstellen, sondern den bestehenden verwenden, würde die resultierende Datei fehlerhaft enden. Es werden die Anzahl der Frames berechnet und ausgeben, und im Anschluss wird die Sample-für-Sample Filterung über die `filterAudio()`-Funktion gestartet. Nach der Filterung werden beide Dateien geschlossen und endet damit das Programm. 

## Filterprozess der WAV-Datei
```cpp
// --- Filterprozess auf Samples der WAV anwenden ---
void filterAudio(uint16_t numChannels, uint32_t dataSize, uint16_t bitsPerSample) {
  uint16_t blockAlign = numChannels * bitsPerSample / 8;
  const int bufferFrames = 512;
  int16_t buffer[bufferFrames * numChannels]; // Zwsichenspeicher für Samples

  uint32_t totalFrames = dataSize / blockAlign;
  uint32_t framesLeft = totalFrames;

  while (framesLeft > 0) {
    int framesToRead = (framesLeft > bufferFrames) ? bufferFrames : framesLeft;
    int bytesToRead = framesToRead * blockAlign;

    // Rohdaten lesen
    int bytesRead = wavFile.read((uint8_t*)buffer, bytesToRead);
    if (bytesRead != bytesToRead) {
      Serial.println("Fehler beim Lesen der Samples.");
      break;
    }

    int samplesInBuffer = bytesRead / 2; // 2 Bytes = 16 Bit pro Sample


    // Samples einzeln filtern
    for (int i = 0; i < samplesInBuffer; i += numChannels) {
      if (numChannels == 1) {
        float filteredSample = filterL.filter((float)buffer[i]);
        buffer[i] = constrain((int)filteredSample, -32768, 32767);
      }
      else {
        float filteredL = filterL.filter((float)buffer[i]);
        float filteredR = filterR.filter((float)buffer[i + 1]);
        buffer[i] = constrain((int)filteredL, -32768, 32767);
        buffer[i + 1] = constrain((int)filteredR, -32768, 32767);
      }
    }
    // Gefilterte Daten in neue Datei schreiben
    filteredFile.write((uint8_t*)buffer, bytesRead);
    framesLeft -= framesToRead;
```

Die `filterAudio`-Funktion führt die Sample-für-Sample-Verabreitung der Audio-Daten durch.

**Blockweise Verarbeitung**: Die Audio-Daten werden in 512-Frame-Blöcken eingelesen, anstatt die gesamte Datei in den Speicher zu laden. Die ermöglicht auch die Verarbeitung großer Dateien mit begrenztem Arbeitsspeicher.

**Filteranwendung**: Jedes der Sample wird durch die digitalen Filter gesendet. Bei Mono wird jeweils jedes Sample durch eine einzige Filterinstanz (`filterL`) verarbeitet. Bei Stereo liegen die 16-Bit-Samples im Interleaved-Format vor, bei welchem sich der linken und rechten Kanalsamples abwechseln(LRLRLR...). Die Schleife springt um `numChannels` Positionen (`i +=numChannels`), wodurch `buffer[i]` stets den linken und `buffer[i]` den rechten Kanal adressiert. Beide Kanäle werden durch separate Filterinstanzen (`filterL` für links, `filterR` für rechts) unabhängig voneinander gefiltert, was die Stereo-Trennung gewährleistet.

**Wertebreichsschutz**: Da digitale Filter die Amplitude verstärken können, werden die gefilterten Werte mit `constrain()` auf den gültigen 16-Bit-Bereich begrenzt. Dies verhindert Übersteuerung und damit verbundene Verzerrungen.

**Kontinuierliche Ausgabe**: Die verarbeiteten Samples werden sofort in die Ausgabedatei geschrieben, wodurch ein kontinuierlicher Datenfluss ohne große Zwischenspeicherung gewährleistet wird.

## Filterkaskadierung

Die Kaskadierung wird durchgeführt, indem die Filterung durch mehrere Stufen durchgeführt wird. Diese Stufen können durch Biquad-Filter oder Segmente einer SOS-Matrix definiert werden.

```cpp
#define NUM_STAGES 2 // Anzahl der Filterstufen

// Erste Sektion
const float gain_s1 = 1.0;
const float b_coefficients_s1[] = { b_0_s1, b_1_s1, b_2_s1};
const float a_coefficients_s1[] = { a_0_s1, a_1_s1, a_2_s1};
// Zweite Sektion
const float gain_s2 = 1.0;
const float b_coefficients_s2[] = { b_0_s2, b_1_s2, b_2_s2};
const float a_coefficients_s2[] = { a_0_s2, a_1_s2, a_2_s2};

BiquadFilterTDF2 filterL[NUM_STAGES] = {
  BiquadFilterTDF2(b_coefficients_s1, a_coefficients_s1, gain_s1),
  BiquadFilterTDF2(b_coefficients_s2, a_coefficients_s2, gain_s2),
};

BiquadFilterTDF2 filterR[NUM_STAGES] = {
  BiquadFilterTDF2(b_coefficients_s1, a_coefficients_s1, gain_s1),
  BiquadFilterTDF2(b_coefficients_s2, a_coefficients_s2, gain_s2),
};
```
Anhand des Parameters `NUM_STAGES` kann die Anzahl der Biquad-Sektionen definiert werden. Jede Sektion hat ihre eigenen `b`- und `a`-Koeffizienten sowie einen `gain`-Parameter mit den entsprechenden Bezeichnungen. Die Filterinstanzierung erfolgt durch Arrays von Biquad-Filtern, wobei jedes Array-Elemement eine separate Filtersstufe mit eigenen Koeffizienten repräsentiert.

Werden identische Filterparameter in mehrere Filterstufen implementiert, wird die Filtercharakteristik der vorherigen Stufe verstärkt. Alternativ können Filter höherer Ordnung implementiert werden, indem die SOS-Matrix etappenweise auf die einzelnen Filterstufen aufgeteilt wird.

```cpp
  // Samples einzeln filtern - KASKADIERT
  for (int i = 0; i < samplesInBuffer; i += numChannels) {
    if (numChannels == 1) {
      float sample = (float)buffer[i];
      for (int s = 0; s < NUM_STAGES; s++) {
        sample = filterL[s].filter(sample);
      }
      buffer[i] = constrain((int)sample, -32768, 32767);
    }
    else {
      float left = (float)buffer[i];
      float right = (float)buffer[i + 1];
      for (int s = 0; s < NUM_STAGES; s++) {
        left = filterL[s].filter(left);
        right = filterR[s].filter(right);
      }
    buffer[i] = constrain((int)left, -32768, 32767);
    buffer[i + 1] = constrain((int)right, -32768, 32767);
  }
```
Bei der kaskadierten Filterung werden die Filterstufen in Serie Implementiert, bei welcher die Samples durch jede Stufe sequenziell verarbeitet werden. Das Ausgangssignal einer Stufe wird zum Eingangssignal der nächsten Stufe, wodurch eine erhöhte Filterordnung oder verstärkte Filterwirkung ermöglicht. Bei Mono druchläuft jedes Sample alle `NUM_STAGES` Filterstufen des `filterL`-Arrays, bei Stereo werden beide Kanäle parallel durch ihre jeweiligen Filterkaskaden(`filterL` und `filterR`) verarbeitet. Nach der kompletten Kaskadierung werden die gefilterten Daten auf den 16-Bit-Bereich begrenzt und zurückgeschrieben.