# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.srcs/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0.xci
# IP: The module: 'audio_test_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.srcs/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0.xci
# IP: The module: 'audio_test_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Virtuel_Folder/boards/Pynq-Z2/base/audio_test_v1/audio_test_v1.gen/sources_1/bd/audio_test/ip/audio_test_rst_ps7_0_100M_0/audio_test_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_test_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
