-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_test_v4_old_IP_test\BiquadFil_ip_1_3_axi4_stream_slave.vhd
-- Created: 2025-05-22 11:48:10
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadFil_ip_1_3_axi4_stream_slave
-- Source Path: BiquadFil_ip_1_3/BiquadFil_ip_1_3_axi4_stream_slave
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadFil_ip_1_3_axi4_stream_slave IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_Slave_TDATA           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Stream_Slave_TVALID          :   IN    std_logic;  -- ufix1
        auto_ready                        :   IN    std_logic;  -- ufix1
        AXI4_Stream_Slave_TREADY          :   OUT   std_logic;  -- ufix1
        user_data                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        user_valid                        :   OUT   std_logic  -- ufix1
        );
END BiquadFil_ip_1_3_axi4_stream_slave;


ARCHITECTURE rtl OF BiquadFil_ip_1_3_axi4_stream_slave IS

  -- Component Declarations
  COMPONENT BiquadFil_ip_1_3_fifo_data
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          Empty                           :   OUT   std_logic;  -- ufix1
          Full                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BiquadFil_ip_1_3_fifo_data
    USE ENTITY work.BiquadFil_ip_1_3_fifo_data(rtl);

  -- Signals
  SIGNAL count_check_slave                : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL count_match_slave                : std_logic;  -- ufix1
  SIGNAL fifo_rd_ack                      : std_logic;  -- ufix1
  SIGNAL stream_in_fifo_user_data         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL fifo_empty                       : std_logic;  -- ufix1
  SIGNAL fifo_full                        : std_logic;  -- ufix1
  SIGNAL stream_in_fifo_user_data_unsigned : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL stream_in_fifo_en_user_data      : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL fifo_empty_neg                   : std_logic;  -- ufix1
  SIGNAL fifo_multirate_empty_neg         : std_logic;  -- ufix1
  SIGNAL fifo_rd_ack_multirate            : std_logic;  -- ufix1
  SIGNAL stream_in_user_valid             : std_logic;  -- ufix1

BEGIN
  u_BiquadFil_ip_1_3_fifo_data_inst : BiquadFil_ip_1_3_fifo_data
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => AXI4_Stream_Slave_TDATA,  -- ufix32
              Push => AXI4_Stream_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => stream_in_fifo_user_data,  -- ufix32
              Empty => fifo_empty,  -- ufix1
              Full => fifo_full  -- ufix1
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 9
  multirate_counter_slave_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count_check_slave <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        IF count_check_slave >= to_unsigned(16#09#, 8) THEN 
          count_check_slave <= to_unsigned(16#00#, 8);
        ELSE 
          count_check_slave <= count_check_slave + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS multirate_counter_slave_process;


  
  count_match_slave <= '1' WHEN count_check_slave = to_unsigned(16#09#, 8) ELSE
      '0';

  fifo_rd_ack <= count_match_slave AND auto_ready;

  AXI4_Stream_Slave_TREADY <=  NOT fifo_full;

  stream_in_fifo_user_data_unsigned <= unsigned(stream_in_fifo_user_data);

  multirate_user_data_slave_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        stream_in_fifo_en_user_data <= to_unsigned(0, 32);
      ELSIF enb = '1' AND fifo_rd_ack = '1' THEN
        stream_in_fifo_en_user_data <= stream_in_fifo_user_data_unsigned;
      END IF;
    END IF;
  END PROCESS multirate_user_data_slave_process;


  user_data <= std_logic_vector(stream_in_fifo_en_user_data);

  fifo_empty_neg <=  NOT fifo_empty;

  multirate_user_data_valid_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        fifo_multirate_empty_neg <= '0';
      ELSIF enb = '1' AND fifo_rd_ack = '1' THEN
        fifo_multirate_empty_neg <= fifo_empty_neg;
      END IF;
    END IF;
  END PROCESS multirate_user_data_valid_process;


  multirate_fifo_rd_ack_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        fifo_rd_ack_multirate <= '0';
      ELSIF enb = '1' AND count_match_slave = '1' THEN
        fifo_rd_ack_multirate <= fifo_rd_ack;
      END IF;
    END IF;
  END PROCESS multirate_fifo_rd_ack_process;


  stream_in_user_valid <= fifo_multirate_empty_neg AND fifo_rd_ack_multirate;

  user_valid <= stream_in_user_valid;

END rtl;

