-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_test_v4_old_IP_test\BiquadFil_ip_1_3_axi4_stream_master.vhd
-- Created: 2025-05-22 11:48:10
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadFil_ip_1_3_axi4_stream_master
-- Source Path: BiquadFil_ip_1_3/BiquadFil_ip_1_3_axi4_stream_master
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadFil_ip_1_3_axi4_stream_master IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_Master_TREADY         :   IN    std_logic;  -- ufix1
        user_data                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        user_valid                        :   IN    std_logic;  -- ufix1
        packet_size_axi4_stream_master    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Stream_Master_TDATA          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Stream_Master_TVALID         :   OUT   std_logic;  -- ufix1
        AXI4_Stream_Master_TLAST          :   OUT   std_logic;  -- ufix1
        auto_ready                        :   OUT   std_logic  -- ufix1
        );
END BiquadFil_ip_1_3_axi4_stream_master;


ARCHITECTURE rtl OF BiquadFil_ip_1_3_axi4_stream_master IS

  -- Component Declarations
  COMPONENT BiquadFil_ip_1_3_fifo_data_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          Empty                           :   OUT   std_logic;  -- ufix1
          AFull                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT BiquadFil_ip_1_3_fifo_TLAST_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic;  -- ufix1
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BiquadFil_ip_1_3_fifo_data_OUT
    USE ENTITY work.BiquadFil_ip_1_3_fifo_data_OUT(rtl);

  FOR ALL : BiquadFil_ip_1_3_fifo_TLAST_OUT
    USE ENTITY work.BiquadFil_ip_1_3_fifo_TLAST_OUT(rtl);

  -- Signals
  SIGNAL count_check_master               : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL count_match_master               : std_logic;  -- ufix1
  SIGNAL out_fifo_push_master             : std_logic;  -- ufix1
  SIGNAL multirate_int_delay_port_tready_reg : std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
  SIGNAL fifo_port_tready                 : std_logic;  -- ufix1
  SIGNAL fifo_afull_data                  : std_logic;  -- ufix1
  SIGNAL internal_ready                   : std_logic;  -- ufix1
  SIGNAL internal_ready_delayed           : std_logic;  -- ufix1
  SIGNAL fifo_push                        : std_logic;  -- ufix1
  SIGNAL AXI4_Stream_Master_TDATA_tmp     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL fifo_empty_data                  : std_logic;  -- ufix1
  SIGNAL packet_size_axi4_stream_master_unsigned : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tlast_size_value                 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_packet_size_strobe           : std_logic;  -- ufix1
  SIGNAL auto_tlast                       : std_logic;  -- ufix1
  SIGNAL reset_TLAST                      : std_logic;  -- ufix1
  SIGNAL tlast_counter_out                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tlast_rel_out                    : std_logic;  -- ufix1

BEGIN
  u_BiquadFil_ip_1_3_fifo_data_OUT_inst : BiquadFil_ip_1_3_fifo_data_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_data,  -- ufix32
              Push => fifo_push,  -- ufix1
              Pop => fifo_port_tready,  -- ufix1
              Out_rsvd => AXI4_Stream_Master_TDATA_tmp,  -- ufix32
              Empty => fifo_empty_data,  -- ufix1
              AFull => fifo_afull_data  -- ufix1
              );

  u_BiquadFil_ip_1_3_fifo_TLAST_OUT_inst : BiquadFil_ip_1_3_fifo_TLAST_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => auto_tlast,  -- ufix1
              Push => fifo_push,  -- ufix1
              Pop => AXI4_Stream_Master_TREADY,  -- ufix1
              Out_rsvd => AXI4_Stream_Master_TLAST  -- ufix1
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 9
  multirate_counter_master_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count_check_master <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        IF count_check_master >= to_unsigned(16#09#, 8) THEN 
          count_check_master <= to_unsigned(16#00#, 8);
        ELSE 
          count_check_master <= count_check_master + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS multirate_counter_master_process;


  
  count_match_master <= '1' WHEN count_check_master = to_unsigned(16#09#, 8) ELSE
      '0';

  out_fifo_push_master <= count_match_master AND user_valid;

  multirate_int_delay_port_tready_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        multirate_int_delay_port_tready_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        multirate_int_delay_port_tready_reg(0) <= AXI4_Stream_Master_TREADY;
        multirate_int_delay_port_tready_reg(8 DOWNTO 1) <= multirate_int_delay_port_tready_reg(7 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS multirate_int_delay_port_tready_process;

  fifo_port_tready <= multirate_int_delay_port_tready_reg(8);

  internal_ready <=  NOT fifo_afull_data;

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        internal_ready_delayed <= '0';
      ELSIF enb = '1' THEN
        internal_ready_delayed <= internal_ready;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  fifo_push <= internal_ready_delayed AND out_fifo_push_master;

  AXI4_Stream_Master_TVALID <=  NOT fifo_empty_data;

  packet_size_axi4_stream_master_unsigned <= unsigned(packet_size_axi4_stream_master);

  const_1 <= to_unsigned(1, 32);

  tlast_size_value <= packet_size_axi4_stream_master_unsigned - const_1;

  reset_TLAST <= reg_packet_size_strobe OR auto_tlast;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  tlast_counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tlast_counter_out <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        IF reset_TLAST = '1' THEN 
          tlast_counter_out <= to_unsigned(0, 32);
        ELSIF fifo_push = '1' THEN 
          tlast_counter_out <= tlast_counter_out + to_unsigned(1, 32);
        END IF;
      END IF;
    END IF;
  END PROCESS tlast_counter_process;


  
  tlast_rel_out <= '1' WHEN tlast_counter_out = tlast_size_value ELSE
      '0';

  auto_tlast <= fifo_push AND tlast_rel_out;

  AXI4_Stream_Master_TDATA <= AXI4_Stream_Master_TDATA_tmp;

  auto_ready <= internal_ready;

END rtl;

