vlib work
vcom  alpha10Gain_src_BiquadDF2Section1.vhd
vcom  alpha10Gain_src_Biquad_Filter.vhd
vcom  alpha10Gain_src_BiquadDF2Section1_block.vhd
vcom  alpha10Gain_src_Biquad_Filter1.vhd
vcom  alpha10Gain_src_Biquad_Filtrer.vhd
