-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_Filter_v7_IP\Butter_HP_4_2500_v1_src_Biquad_Filtrer.vhd
-- Created: 2025-06-11 17:00:00
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.08333e-05
-- Target subsystem base rate: 2.08333e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.08333e-05
-- Out2                          ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Butter_HP_4_2500_v1_src_Biquad_Filtrer
-- Source Path: biquad_Filter_v7_IP/Biquad Filtrer
-- Hierarchy Level: 0
-- Model version: 1.93
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Butter_HP_4_2500_v1_src_Biquad_Filtrer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        In2                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Out2                              :   OUT   std_logic
        );
END Butter_HP_4_2500_v1_src_Biquad_Filtrer;


ARCHITECTURE rtl OF Butter_HP_4_2500_v1_src_Biquad_Filtrer IS

  -- Component Declarations
  COMPONENT Butter_HP_4_2500_v1_src_Biquad_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Butter_HP_4_2500_v1_src_Biquad_Filter1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Butter_HP_4_2500_v1_src_Biquad_Filter
    USE ENTITY work.Butter_HP_4_2500_v1_src_Biquad_Filter(rtl);

  FOR ALL : Butter_HP_4_2500_v1_src_Biquad_Filter1
    USE ENTITY work.Butter_HP_4_2500_v1_src_Biquad_Filter1(rtl);

  -- Signals
  SIGNAL Biquad_Filter_out1               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Biquad_Filter_out2               : std_logic;
  SIGNAL Biquad_Filter1_out1              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Biquad_Filter1_out2              : std_logic;

BEGIN
  u_Biquad_Filter : Butter_HP_4_2500_v1_src_Biquad_Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => In1,  -- sfix32_En16
              validIn => In2,
              dataOut => Biquad_Filter_out1,  -- sfix32_En16
              validOut => Biquad_Filter_out2
              );

  u_Biquad_Filter1 : Butter_HP_4_2500_v1_src_Biquad_Filter1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => Biquad_Filter_out1,  -- sfix32_En16
              validIn => Biquad_Filter_out2,
              dataOut => Biquad_Filter1_out1,  -- sfix32_En16
              validOut => Biquad_Filter1_out2
              );

  ce_out <= clk_enable;

  Out1 <= Biquad_Filter1_out1;

  Out2 <= Biquad_Filter1_out2;

END rtl;

