-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_test_v4_old_IP_test\BiquadFil_ip_src_Biquad_Filtrer_tc.vhd
-- Created: 2025-05-22 11:27:46
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadFil_ip_src_Biquad_Filtrer_tc
-- Source Path: Biquad_Filtrer_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb_60_1_0  : identical to clk_enable
-- enb         : 60x slower than clk with last phase
-- enb_1_1_1   : 60x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadFil_ip_src_Biquad_Filtrer_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb_60_1_0                        :   OUT   std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic
        );
END BiquadFil_ip_src_Biquad_Filtrer_tc;


ARCHITECTURE rtl OF BiquadFil_ip_src_Biquad_Filtrer_tc IS

  -- Signals
  SIGNAL count60                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1                            : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_1_1_1                      : std_logic;

BEGIN
  enb_60_1_0 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 59
  counter_60_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count60 <= to_unsigned(16#01#, 6);
      ELSIF clk_enable = '1' THEN
        IF count60 >= to_unsigned(16#3B#, 6) THEN 
          count60 <= to_unsigned(16#00#, 6);
        ELSE 
          count60 <= count60 + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_60_process;


  
  comp_0_tmp <= '1' WHEN count60 = to_unsigned(16#3B#, 6) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1 <= phase_0 AND clk_enable;

  enb <= enb_1;

  
  comp_1_tmp <= '1' WHEN count60 = to_unsigned(16#00#, 6) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_1_1_1 <= phase_1 AND clk_enable;

  enb_1_1_1 <= enb_1_1_1_1;

END rtl;

