-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_test_v4_old_IP_test\BiquadFil_ip_src_Biquad_Filtrer.vhd
-- Created: 2025-05-22 11:27:46
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.77929e-07
-- Target subsystem base rate: 3.77929e-07
-- Explicit user oversample request: 60x
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.26757e-05
-- Out2                          ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadFil_ip_src_Biquad_Filtrer
-- Source Path: biquad_test_v4_old_IP_test/Biquad Filtrer
-- Hierarchy Level: 0
-- Model version: 1.74
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadFil_ip_src_Biquad_Filtrer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        In2                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Out2                              :   OUT   std_logic
        );
END BiquadFil_ip_src_Biquad_Filtrer;


ARCHITECTURE rtl OF BiquadFil_ip_src_Biquad_Filtrer IS

  -- Component Declarations
  COMPONENT BiquadFil_ip_src_Biquad_Filtrer_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb_60_1_0                      :   OUT   std_logic;
          enb                             :   OUT   std_logic;
          enb_1_1_1                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT BiquadFil_ip_src_Biquad_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BiquadFil_ip_src_Biquad_Filtrer_tc
    USE ENTITY work.BiquadFil_ip_src_Biquad_Filtrer_tc(rtl);

  FOR ALL : BiquadFil_ip_src_Biquad_Filter
    USE ENTITY work.BiquadFil_ip_src_Biquad_Filter(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_1_1                        : std_logic;
  SIGNAL enb_60_1_0                       : std_logic;
  SIGNAL Biquad_Filter_out1               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Biquad_Filter_out2               : std_logic;

BEGIN
  u_Biquad_Filtrer_tc : BiquadFil_ip_src_Biquad_Filtrer_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb_60_1_0 => enb_60_1_0,
              enb => enb,
              enb_1_1_1 => enb_1_1_1
              );

  u_Biquad_Filter : BiquadFil_ip_src_Biquad_Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => In1,  -- sfix32_En16
              validIn => In2,
              dataOut => Biquad_Filter_out1,  -- sfix32_En16
              validOut => Biquad_Filter_out2
              );

  ce_out <= enb_1_1_1;

  Out1 <= Biquad_Filter_out1;

  Out2 <= Biquad_Filter_out2;

END rtl;

