-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\biquad_test_v4_old_IP_test\BiquadFil_ip_1_4_src_Biquad_Filtrer_tc.vhd
-- Created: 2025-05-22 12:09:37
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadFil_ip_1_4_src_Biquad_Filtrer_tc
-- Source Path: Biquad_Filtrer_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_10_0  : 10x slower than clk with last phase
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadFil_ip_1_4_src_Biquad_Filtrer_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_10_0                        :   OUT   std_logic
        );
END BiquadFil_ip_1_4_src_Biquad_Filtrer_tc;


ARCHITECTURE rtl OF BiquadFil_ip_1_4_src_Biquad_Filtrer_tc IS

  -- Signals
  SIGNAL count10                          : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1_10_0_1                     : std_logic;

BEGIN
  enb <= clk_enable;

  enb_1_1_1 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 9
  counter_10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count10 <= to_unsigned(16#1#, 4);
      ELSIF clk_enable = '1' THEN
        IF count10 >= to_unsigned(16#9#, 4) THEN 
          count10 <= to_unsigned(16#0#, 4);
        ELSE 
          count10 <= count10 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_10_process;


  
  comp_0_tmp <= '1' WHEN count10 = to_unsigned(16#9#, 4) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_10_0_1 <= phase_0 AND clk_enable;

  enb_1_10_0 <= enb_1_10_0_1;

END rtl;

